version: '3.2'
services:
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
    depends_on:
      - mysql-db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql-db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

  mysql-db:
    image: mysql
    ports:
      - 3306:3306
    container_name: mysql-db
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sonar
      - MYSQL_DATABASE=sonar
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
    command: mysqld --max_allowed_packet=30M

  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./data/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube

  gitlab-ce:
    build:
      context: gitlab-ce/
    restart: always
    hostname: 'ci-cd.dockerdonegal.ie'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ci-cd.dockerdonegal.ie'
    ports:
      - '80:80'
      - '22:22'
    container_name: gitlab-ce
    volumes:
      - './data/gitlab/config:/etc/gitlab'
      - './data/gitlab/logs:/var/log/gitlab'
      - './data/gitlab/data:/var/opt/gitlab'